spring.application.name=processor-service

server.port=8086

springdoc.swagger-ui.path=/swagger-ui.html

services.action.url=http://action-service:8083
services.metric.url=http://metric-service:8082
services.loader.url=http://loader-service:8084

sender.email.url=http://sender-email-service:8087/api/email/send
sender.sms.url=http://sender-sms-service:8088/api/sms/send
logger.service.url=http://logger-service:8090/api/logs