apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
        - name: evaluation-service
          image: mohamad1111/evaluation-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
spec:
  type: NodePort
  selector:
    app: evaluation-service
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30085
