spring.application.name=security-service

server.port=8089

services.user.url=http://localhost:8081

jwt.secret-base64=/x1zslxIBnH2ixadXLb2F7uKVBNotxT6nCrF6dD3O/s=
jwt.expiration-minutes=60

springdoc.swagger-ui.path=/swagger-ui.html